---
- include_tasks:                        '../tasks/install_packages.yml'
- include_tasks:                        '../tasks/user_groups.yml'
- include_tasks:                        '../tasks/users.yml'
- include_tasks:                        '../tasks/shell_commands.yml'
  when:                                 users_result.changed
- include_tasks:                        '../tasks/template_files.yml'
- include_tasks:                        '../tasks/enable_services.yml'
- include_tasks:                        '../tasks/restart_services.yml'
  when:                                 template_files_result.changed
- include_tasks:                        '../tasks/start_services.yml'
